### ISSUE TITLE
swatchseries.to: Script does not redirect properly

### ISSUE THREAD

**Issue by stapuft** [andrewjmetzger/better-watchseries#15]
when you click a link to watch a video, instead of automatically clicking the big blue button, and taking you to the source, https://www1.swatchseries.to, instead takes you back to the main page.
I think they made some changes to the site, because now if you have an adblocker on, the blue button doesn't even appear to click, when this userscript is disabled.

and no, the userscript still does the same thing (redirects you to the main page instead of your video) with adblocker disabled.

**Comment by andrewjmetzger** [comment]
Interesting that this occurs even with the ad-blocker disabled. Looking into the code of the page with the big blue button, it appears that the site dynamically injects a dummy button linking back to the homepage.

The only way to counter this that I can think of would be to block the offending inline script, which is:
```html

// var params = window.location.search.replace("?", "");
// var decoded = $.base64.decode(params.substr(2));
decoded = "http://www1.swatchseries.to/";
document.write('<a href="' + decoded + '" class="push_button blue" style="display: none;width:290px; height:70px; font-weight:normal; font-size:22px; line-height:65px; margin:0px auto 20px auto;">Click Here to Play</a>');
```

Sadly, [uBlock Origin](https://github.com/gorhill/uBlock/), the one ad-blocker I know of with support for inline script filtering, says that [inline-script filtering is not currently possible in Chromium-based browsers](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#caveats):

> **Caveats:**
> Not supported in Chromium-based browser.
> - Starring the related Chromium issue may help motivate Chromium devs to implement support.
> - Falling back on wholesale blocking of all inline script tags may work.

Alas, wholesale blocking *all* inline scripts prevents the real "Click here to play" button from rendering.

At this point, I do not see a straightforward way of bypassing the dummy play button. You can of course try to block the above inline script with Firefox and uBlock Origin to see if that works. However, keep in mind that BWS is only supported in Chromium-based browsers.

**If you or anyone else has experience with circumventing this kind of tactic, please feel free to submit a Pull Request.** Until then, I will be removing `swatchseries.to` from the ist of supported sites. Please update your copy of BWS to the latest version, so that the script no longer runs on `swatchseries.to`.

***Edit to add:***  The script will no longert automatically click the big blue button on swatchseries.to. However, the script will continue to function as expected on supported video hosts.

**Comment by stapuft** [comment]
okay, cool, good thing I am on Firefox then, so I can just add that bit of offending code to my ublock origin blacklist?
like this?


```
! 11/13/2019 https://www1.swatchseries.to
||static.swatchseries.to/templates/default/images/bk-bluenew.jpg$image
||static.swatchseries.to/templates/default/images/bk-bluenew.jpg$image
||static.swatchseries.to/templates/default/images/casing-tr-classic.gif$image
||static.swatchseries.to/templates/default/images/bk-bluenew.jpg$image
||static.swatchseries.to/templates/default/images/tr.png$image
||static.swatchseries.to/templates/default/images/tr.png$image
// var params = window.location.search.replace("?", "");
// var decoded = $.base64.decode(params.substr(2));
decoded = "http://www1.swatchseries.to/";
document.write('<a href="' + decoded + '" class="push_button blue" style="display: none;width:290px; height:70px; font-weight:normal; font-size:22px; line-height:65px; margin:0px auto 20px auto;">Click Here to Play</a>');
```

I usually just use the context menu to block offending items...sorry if this is a stupid question. I've been using your userscript for years, and its made using this site so much easier, I would hate to have to try to find a replacement website/script now LOL

**Comment by andrewjmetzger** [comment]
Hi stapuft, thanks for your reply!

> so I can just add that bit of offending code to my ublock origin blacklist?

Hey now, that's not a stupid question at all. In fact, it's a very good one! 
Unfortunately, I'm not all too familiar with inline script filtering. However, [according to the uBlock Origin documentation](https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering#overview), the syntax is something like:

```javascript
##^script:has-text(code-to-block)
```
... which would theoretically block any `<script> ... </script>` tags containing `code-to-block` somewhere in the page's source. So, the whole thing should most likely be on one line. 

Since it seems to be a basic "contains" filter, try just specifying a part of the script. For instance, specify the invisible big blue button like so:
```javascript
##^script:has-text('class="push_button blue" style="display: none;')
```

If the line above doesn't work, try another section of the script. Remember to either use single quotes `'`, or escape any `"` double quotes with a backslash `\"`.

All of  that said, I do not have access to a test environment for this, owing to the (ahem) *ethical grey area* this project occupies. Hence, it is only officially supported via Tampermonkey, and also only in Chromium-based browsers.


***NOTE:*** To test the uBlock Origin rule, you will need to **manually downgrade** to an older version of BWS that supports `swatchseries.to`. Uninstall your current version of BWS, then [install v2.8.0 from here](https://github.com/andrewjmetzger/better-watchseries/raw/3e913caefede2f246f443a16e22445270a72eac5/better-watchseries.user.js), making sure to **disable automatic updates for BWS only**.

You may see a screen asking if you're sure you want to downgrade. Please do so to test the uBlock rule:
![image](https://user-images.githubusercontent.com/590246/68811436-a1c4f500-063e-11ea-9b47-4e4772616c13.png)


---

> I've been using your userscript for years, and its made using this site so much easier, 

Awesome! Glad to see at least some of my work making an impact. :) Thank you for the kind words.

> I would hate to have to try to find a replacement website/script now

Understandable. Honestly, if you're able to download the content (even temporarily) instead of just streaming it, you'd have *many* more options. Again, that probably isn't the best discussion to be having on GitHub, so if you'd like, shoot me an **email** (at `andrew@mtz.gr`). 

I'm also on **Discord**, if you'd prefer that; search for `prokill2011#2087`. Either way, feel free to reach out, and we can find an option that works better for you. :)

**Comment by stapuft** [comment]
that bit of code, blocks the script that hides the button when adblock is enabled, but it also blocks your redirect script from running at all, on V2.8.0 of your userscript.
OK I can do that ill be hitting you up on discord then, and ill close this issue aswell.
[Personal information redacted].

**Comment by andrewjmetzger** [comment]
***UPDATE:*** **Although `swatchseries.to` is no longer supported, you may find `watchseries.si` an acceptable alternative.**

Support has been added for `watchseries.si`.
